version: '3.4'

services:
  databaseapi:
    image: ${DOCKER_REGISTRY-}databaseapi
    build:
      context: .
      dockerfile: DataBaseApi/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"